### PR TITLE
Showing PDF files by URL

### PR DESCRIPTION
**Pull request by achatina**
I made a class that helps with showing pdf files from network. 
A sample usage also provides in a sample project. 
It will help developers to download files without redundant code with your library.

### CODE REVIEW

**Comment by barteksc** [comment]
Thank you for contribution.
The problem is that on every configuration change (eg. orientation change), download process starts again and previous one is not finished - downloading process must be aware of Activity lifecycle.
You also forgot to add `ACCESS_NETWORK_STATE` and `INTERNET` permissions, but this is minor issue.

**Comment by achatina** [comment]
@imBalasankar Thanks. But it's not complete at all. No time for it. Maybe someone will continue this

**Comment by fukemy** [comment]
hello, do y have gradle link to import?

**Comment by achatina** [comment]
@fukemy hi!
Unfortunately - no. The best solution will be download file by yourself and pass local file into it. It's not very difficult and will not take much time

**Comment by fukemy** [comment]
yes i downloaded and load successful, but i hope there have url pdf preview, in ios they do it for us, anyway, ur lib is best and easy to use, thanks

**Pull request closed without merging**
