### PR TITLE
Page Borders/Markers and more....

### PR DESCRIPTION
**Pull request by 1stmetro**
Its been a while since i amended this code and been to busy to post it, it includes the ability to add page borders/markers and to be able to set colours to any required by the user and also change the size of the border.

As you can see below i set the colour in preferences but you can set this using an integer, you can also set the height or width of this border between pages so you give that appearance that a page has been changed like a book.

You could just set the colour and the size of the border statically but i allow the client to amend this hence the sample on my code shown below.

Constants.SHOW_BORDER = true;
Constants.BORDER_COLOR = prefs.getInt("pdf_bordercolor",R.color.white);
Constants.BORDER_WIDTH = prefs.getInt("pdf_bordersize", "1");

### CODE REVIEW

**Comment by barteksc** [comment]
After pulling your code there is some duplicated `Constants` class and errors in `PDFView` class

**Comment by 1stmetro** [comment]
I did write it some time ago so think I added a bit then added some more without comparing to my recent code when I get the chance will update fully, min edition is page borders, width colour etc but I'm sure there is other amendments in there also.

**Comment by barteksc** [comment]
There is still duplicated `Constant` class

**Comment by barteksc** [comment]
What is BookMode? It is used only in `fitToWidth()` method.

**Comment by barteksc** [comment]
Setting `Constants.SHOW_BORDER` to `true` causes document to disappear, whole canvas in white. Please test your code before pushing

**Comment by 1stmetro** [comment]
Im running the code on 3 or 4 devices it actually works fine for me white border black border etc different sizes etc. Did you set the color before turning on the border? Bit strange you lose your pdf.. i have not had that problem.

Book mode I forget and unable to view the code currently.

**Comment by Pajet** [comment]
I still have an error on !BookMode and class Constants is duplicate. Plse assist here @barteksc @1stmetro

**Comment by 1stmetro** [comment]
Probably a mix of additions, what's the error and where does it point you the version I use works fine, not sure how to renew my fork to update it

**Comment by barteksc** [comment]
@1stmetro You may close this pull request and create new one, current sources are broken

**Pull request closed without merging**
